List<String> categories = [
  'Mobile',
  'Laptops',
  'Accessories',
  'Property for sale',
  'Property for Rent',
      'Cars',
  'Motorcycles',
      'Jobs',
  'Other Vehicles',
  'Electronics',
  'Electrical & Power Tools',
  'Home Appliances',
  'Music & Instruments',
  'Furniture',
  'Clothing',
  'Beauty & Personal Care',
  'Health & Fitness',
  'Books',
  'Sports Equipment',
  'Kids',
  'Services',
  'Pets',
  'Travel & Tourism',
  'Food & Beverages',
];