List<String> districtNames = [
  'Attock',
  'Badin',
  'Bahawalnagar',
  'Bahawalpur',
  'Bajaur Agency',
  'Bannu',
  'Barkhan',
  'Bhakkar',
  'Buner',
  'Chagai',
  'Chakwal',
  'Charsadda',
  'Chiniot',
  'Chitral',
  'Dera Bugti',
  'Dera Ghazi Khan',
  'Diamer',
  'Dera Ismail Khan',
  'Faisalabad',
  'Ghanche',
  'Ghotki',
  'Gilgit',
  'Gujranwala',
  'Gujrat',
  'Gwadar',
  'Hafizabad',
  'Hangu',
  'Haripur',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jafarabad',
  'Jhal Magsi',
  'Jhang',
  'Jhelum',
  'Kalat',
  'Kandhkot-Kashmore',
  'Karachi Central',
  'Karachi East',
  'Karachi South',
  'Karachi West',
  'Karak',
  'Kasur',
  'Kech',
  'Khairpur',
  'Khanewal',
  'Kharan',
  'Khushab',
  'Khuzdar',
  'Kohat',
  'Kohistan',
  'Kohlu',
  'Kurram Agency',
  'Lahore',
  'Lakki Marwat',
  'Lasbela',
  'Layyah',
  'Lodhran',
  'Loralai',
  'Malakand Agency',
  'Mandi Bahauddin',
  'Mansehra',
  'Mardan',
  'Mastung',
  'Mianwali',
  'Mirpur Khas',
  'Multan',
  'Muzaffargarh',
  'Nankana Sahib',
  'Narowal',
  'Naseerabad',
  'Naushahro Feroze',
  'Nawabshah',
  'North Waziristan Agency',
  'Nowshera',
  'Okara',
  'Orakzai Agency',
  'Panjgur',
  'Peshawar',
  'Pishin',
  'Punjab',
  'Qilla Abdullah',
  'Qilla Saifullah',
  'Quetta',
  'Rahim Yar Khan',
  'Rajanpur',
  'Rawalpindi',
  'Sahiwal',
  'Saidu Sharif',
  'Sanghar',
  'Sargodha',
  'Shaheed Benazirabad',
  'Shangla',
  'Sheikhupura',
  'Sherani',
  'Sialkot',
  'Sibi',
  'Sujawal',
  'Sukkur',
  'Swabi',
  'Swat',
  'Tando Allahyar',
  'Tando Muhammad Khan',
  'Tank',
  'Tharparkar',
  'Thatta',
  'Timergara',
  'Toba Tek Singh',
  'Torghar',
  'Turbat',
  'Umerkot',
  'Upper Dir',
  'Washuk',
  'Zhob',
  'Ziarat',
];
